google_analytics_id: UA-48289017-1
copyright: videoadblock.github.io/myspass
project_name: MySpass Unblocker
desc: Mit dem MySpass Unblocker Plugin werden automatisch alle Videos von Werbung oder Adblock Warnungen befreit.