google_analytics_id: UA-48289017-1
google_analytics_url: myspassunblocker.github.io
copyright: myspassunblocker.github.io
project_name: MySpass Unblocker
desc: Mit dem MySpass Unblocker Chrome Plugin werden automatisch alle Videos von Werbung oder Adblock Warnungen befreit.